### PR TITLE
v1.1.1 - introduce self Ock

### PR DESCRIPTION
**Pull request by ock-mallow**
### 1.1.1
- [x] Introduce self Ock

@alex-mallow @dew-mallow @jk-mallow @jd-mallow @seok-mallow @injunock

### CODE REVIEW

**Comment by jk-mallow** [comment]
LGTM
welcome

**Comment by alex-mallow** [comment]
LGTM

**Comment by dew-mallow** [comment]
LGTM

**Comment by jd-mallow** [comment]
LGTM

**Comment by seok-mallow** [comment]
LGTM
수고하셨습니다.

**Pull request merged**
