### PR TITLE
v0.9.8 - Introduce start

### PR DESCRIPTION
**Pull request by dew-mallow**
### I added the following information. I know you're busy, but I'd appreciation

- [x] Introduce self - dew
- [x] change tom profile
- [x] add tiger agile
---
- Please check the STG distribution part along with the code.
- [x] https://oss-cashmallow.web.app/team/tiger/#member

### CODE REVIEW

**Comment by tom-mallow** [comment]
LGTM

# Welcome to Tiger's Cave.
I need to ask you a big favor.
- From the link below, 
- Agile Practice, Pair programming, TDD, BDD
Please add it.

- https://oss-cashmallow.web.app/team/tiger2agile/#tiger-agile-practice

and

Please change Tom's profile to 300x300 below.
https://github.com/oss-cashmallow/oss-cashmallow.github.io/issues/16

**Comment by tom-mallow** [comment]
+1

**Comment by alex-mallow** [comment]
Welcome to Cashmallow

**Comment by tom-mallow** [comment]
- https://lgtm.fun/

LGTM

**Comment by musk-mallow** [comment]
Welcome to Cashmallow

**Pull request merged**
